
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jayanrlon-nodelet-int-profile-dynamic-2
  namespace: argocd
  finalizers:
  # This solves issue #17
  - resources-finalizer.argocd.argoproj.io/foreground
spec:
  syncPolicy:
    automated:
      prune: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/jayanth-tjvrr/int-test
    path: profiles/dynamic-2/mgmt
    targetRevision: HEAD
    helm:
      parameters:
      - name: clusterName
        value: jayanrlon-nodelet-int
      - name: profileAppName
        value: jayanrlon-nodelet-int-profile-dynamic-2
